### ISSUE TITLE
React-Router Reload on State Change

### ISSUE THREAD

**Issue by rolfea** [rolfea/congress-front-end#15]
When a new state is selected from the drop down menu, react-router should automatically reload the page without the user needing to click on the Senate or Rep. buttons, respectively.

**Comment by rolfea** [comment]
ping @bdougie

**Comment by rolfea** [comment]
I think I have a solution based on this SO: http://stackoverflow.com/questions/31079081/programmatically-navigate-using-react-router and the corresponding entry in the react-router documentation: https://github.com/ReactTraining/react-router/blob/master/docs/guides/NavigatingOutsideOfComponents.md  
  
I should be able to call <code>browserHistory.push(\`/house${"?state=" + selectedState}\`)</code> which should theoretically push the selected state into the URL search query.  
  
My first attempt to resolve was to try to abstract the `setState` into a separate function followed by a "pushBrowserHistory" function in the handleChange function in App.js:  
```
handleChange = (event, index, value) => {
  setSelectedState(value)
  pushBrowserHistory()
}
```  
This didn't work, and I'm not sure if it is an incorrect understanding of working with the arrow functions with ES6 or something else is wrong with my assumptions here.

Second, I thought I could use ComponentDidUpdate function in my App.js file to trigger the `browserHistory.push` approach but the change event from the StateListComponent doesn't seem to constitute an "update" in react, I'm assuming because the event is happening within a different component, the StateListComponent.  
  
Is there a way to modify the handleChange function so that it can first reset the state and then push to the browser history?

**Comment by bdougie** [comment]
Your functions probably need `this` added, though without see what is in them makes it hard to say. I can say, when I did the following it worked. 

```js
  handleChange = (event, index, value) => {
    this.setState({selectedState: value}, browserHistory.push(`/senate?state=${value}`))
  };
```

So as long as your functions have `this` you should be good to go.

**Comment by rolfea** [comment]
This was resolved with the add-dropdown-list PR.
