### ISSUE TITLE
README needs to be updated

### ISSUE THREAD

**Issue by bdougie** [rolfea/congress-front-end#8]
The current README is full of boiler from CRA and it should be focused on the cloning and setup congress-front-end

**Comment by rolfea** [comment]
Working on this today. Is there a good way to test if my installation instructions are correct besides uninstalling the entire app and seeing if the instructions get it running?  
  
Also I want to confirm that npm will install all the dependencies listed in the package.json when a user runs `npm install` and that they wouldn't need to install react-scripts separately before that.

**Comment by bdougie** [comment]
The Best way is getting someone else to run through it. Perhaps see if anyone in the Bloc slack wants to clone a React app. This would also help to get eyes on the project to see if there is a better approach that we haven't thought of. 

Also part of this checkpoint https://www.bloc.io/users/alex-rolfe/checkpoints/1841?roadmap_section_id=138

**Comment by rolfea** [comment]
Added a basic README with details on installation and a code of conduct.
